### DISCUSSION TITLE
Resetting stats

### DISCUSSION THREAD

**Discussion by quasiquote1** [sparcians/map#338] [Q&A] [answered]
Hi,

Is there an easy way to reset the stats that belong to the Unit's statistic set?

I am trying to find a solution to a problem where stats are being incremented in the "warmup" phase of my simulation, but I want to clear the stats when I reach the end of my warmup phase and before I start real timing simulation where the stats collection matters.

Thanks!

**Comment by klingaard** [comment, marked as answer]
Yes... and no.  😃 

How are you getting statistical reports from the simulator?  Are you using the end-of-simulation stats (auto-summary)?  If so, you can't "reset" those stats.  

But you can generate a statistical report that "starts" after your warmup period has elapsed.  This is only supported using the 
```
--report DEF_FILE | PATTERN DEF_FILE DEST [FORMAT]
```
command line option.

Using this option, you can create customized reports, in [different formats](https://sparcians.github.io/map/report_out_format.html) using a custom [definition file](https://sparcians.github.io/map/report_def_format.html).

As an example of what you want to do...  let's say you're running the `sparta_core_example` and you want to start a report after 100 instructions have elapsed (a warmup).  First, create the report definition file:

```
% cat > simple_report.rrep
content:
  report:
    def_file: simple_stats.yaml
    dest_file: simple_report.text
    format: text
    trigger:
      start:
        top.cpu.core0.rob.stats.total_number_retired >= 100
```
Then, create a yaml file detailing what stats you want collected for that report:
```
% cat > simple_stats.yaml
content:
  subreport:
    name: AUTO
    content:
      autopopulate: true
```
The keywords are documented in the online [documentation for reports](https://sparcians.github.io/map/report_def_format.html).

Now, run the simulator:
```
% ./sparta_core_example --report simple_report.rrep -i 200 --auto-summary off
Running...
     [trigger] Now starting report 'simple_stats.yaml on _SPARTA_global_node_' after warmup delay of 100 on counter: <top.cpu.core0.rob.stats.total_number_retired val:100 normal vis:100000000>. Occurred at tick 342 and cycle 342 on clock <Clock Root period=1>
...
Run Successful!
Saving reports...
  [out] Wrote Final Report Report def "simple_stats.yaml" on node "_global" -> "simple_report.text" (format=text) (updated 1 times):
  1 reports written
```
Now, if you look at the generated report, you'll notice that only 100 instructions worth of stats were collected:
```
% grep total_number_retired simple_report.text 
              total_number_retired = 100
```

What the report mechanism does is collect a baseline of the stats at each starting trigger point for each report requested.  Behind the scenes, the report mechanism "resets" the stats at the beginning point of the warmup.  But the actual stats are _not touched_.  This is important because you might want multiple reports starting at different locations.

**Comment by klingaard** [comment]
To make this more interesting, the framework supports "yaml replacements" in case you have different warmup periods for different workloads.   This allows you to use 1 report definition file for multiple disparate runs.  To use yaml replacements:
```
--report-yaml-replacements <placeholder_name> <value> <placeholder_name> <value> ...
```
First, in your report definition file, add a yaml replacement.  This is a variable that begins and ends with '%':
```
% cat > simple_report.rrep
content:
  report:
    def_file: simple_stats.yaml
    dest_file: simple_report.text
    format: text
    trigger:
      start:
        top.cpu.core0.rob.stats.total_number_retired >= %WARMUP%
 ```
Now, run the simulator with the variable "swapped out":
```
% ./sparta_core_example --report simple_report.rrep -i 200 \
    --report-yaml-replacements WARMUP 100 \
    --auto-summary off
```
You should get the same report as in the example above.
