### DISCUSSION TITLE
Best Practice for Parameters used multiple places in the ResourceTree

### DISCUSSION THREAD

**Discussion by timsnyder** [sparcians/map#541] [Q&A]
Let's say you have something the config dumper would show as:
```
top:
    parent:
        params:
              meaning_of_the_universe: 42
        childA:
              params:
                    fooA: whatever
        childB:
              params:
                    fooB: morejunk
```

Now, let's say that `parent`, `chlidA` and `childB` all have behavior that depends on `top.parent.params.meaning_of_the_universe`, what's the best way for `childA` and `childB` to access the param?

There are also more convoluted cases where you have cousins spread out in the tree that need to know about each others' parameters.  I know that depending on how you do this, you can run into tree build order issues if you walk the tree trying to look up parameter values.

Would it be useful for different Resources to be able to register as Observers of a View of other Resources' parameters?  Or, is this intentionally not provided because it runs afoul of the Sparta design?
