### ISSUE TITLE
Support for arbitrary header and fix warmup header value

### ISSUE THREAD

**Issue by MichaelSchoenfelder-SiV** [sparcians/map#279]
This issue reports a bug and a new feature that provides an alternative, since the bug probably isn't fixable in sparta.

**The bug**
`my_sparta_sim --report reports/report_warmup.yaml --report-yaml-replacements  WARMUP_INSTS 29223  --report reports/time_series_crit_warmup.yaml --report-yaml-replacements WARMUP_INSTS 29223 TS_PERIOD 10 `
where
```
content:
  report:
    pattern: top
    def_file: reports/crit_stats.yaml
    dest_file: foo.csv
    format: csv
    trigger:
      start:  core_complex.core.retire.stats.insts_retired >= %WARMUP_INSTS%
      update-count: top.core_complex.core.retire.stats.insts_retired %TS_PERIOD%
```
results in a header of
```
# report="reports/crit_stats.yaml on top",start=39467,end=SIMULATION_END,report_format=csv
# enabled=none,period=10,after=29230,type=aligned_icount,counter=top.core_complex.core.retire.stats.insts_retired,terminate=none,warmup=18446744073709551615
```
Note the value of "warmup=" at the end of the 2nd line.  That's the problem.

I think that value comes from a bespoke usage of an earlier version of the reporting susbsystem that no longer makes sense.

**New Feature Request**
Add a generic way to provide report metadata for the header, as in:
```
content:
  report:
     header_metadata:
      stats_warmup:  %STATS_WARMUP%
      hostname: %HOSTNAME
```
where the `%%` tags would be replaced at simulation time via `--report-yaml-replacements`.
Ideally, the keys under "header_metadata" are not keywords, but arbitrary keys specified in the report description yaml.
These key value pairs shall be placed the report header, formatted appropriately for the json and csv report formats.

**Comment by MichaelSchoenfelder-SiV** [comment]
In the `placeholders.yaml` example, that "CORE0_WARMUP" is just a string replacement for a trigger definition.  SPARTA doesn't really have the concept of "warmup", right?  The "warmup=" string in the CSV report is, in hindsight, a hack that I twisted Dave's arm into implementing before the report definition paradigm was changed.

So now, I am asking two things:
1) remove whatever code is printing the "warmup=" because I suspect it doesn't make sense any more
2) add support for generic header information; you gave a nice suggestion on format

The sparta user will determine the semantics of the strings in the header.

(As I contemplated this right now, I think the "after=" string is providing us information on the trigger and is influenced by the "type=aligned_icount".  I am fairly sure those features were added after the "warmup=" arm twist.  They are nice, but for the application I have in mind, I would actually _not_ have a trigger.   I want to pass a value to `stats_warmup:  %STATS_WARMUP%` to use in plotting a waveform that starts at cycle zero but places an indicator at the "stats_warmup" value.  It is convenient to have this value in the stats output so my app (or Plato) won't have to cross-reference to other files.)

**Comment by klingaard** [comment]
Ah, I see.  I briefly saw these command line options, but failed to notice the word `DEPRECATED`.  😆 
```
  --report-warmup-icount                                                               DEPRECATED
  --report-warmup-counter                                                              DEPRECATED
```
I'll remove these command line options when I removed the "whatever" code that is printing the warmup.   

I'll then start work on the meta data.

**Comment by klingaard** [comment]
So, need an opinion here. 

This is what I'm thinking is valid YAML report definition with metadata:
```
name: "Report1"
author: "Knute"
metadata:
    value1: 1
    value2: "val2"
content:
    subreport:
          .......
```
This will be illegal:
```
name: "Report1"
author: "Knute"
content:
    metadata:
        value1: 1
        value2: "val2"
    subreport:
          .............
```
In other words, metadata cannot be defined within a content.  And cannot be defined twice.  Thoughts?
