### ISSUE TITLE
Allow for optional content in a report file

### ISSUE THREAD

**Issue by klingaard** [sparcians/map#507]
Would be really handy to use the same report definition file for multiple configurations that might or might not have the same stats.  Today the report definition causes the framework to error:
```
Unable to parse expression: "cpu.icache.stats.il1_cache_misses" within context: top in report file "report.yaml" for the following reason: 
SPARTA was unable to find a tree node that matched this name.
```
Here's what the report.yaml looks like:
```
name: "Summary ICache Report"
content:
  cpu.icache.stats.il1_cache_misses: ICache Misses
```
This works for architecture A which has the icache at the `cpu` level, but not architecture B which has it maybe inside `fetch`.

Suggested "fix":
```
name: "Summary ICache Report"
optional_content:
  # Works for arch A
  cpu.icache.stats.il1_cache_misses: ICache Misses
optional_content:
  # Works for arch B
  cpu.fetch.icache.stats.il1_cache_misses: ICache Misses
```
